### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by rennanprysthon** [rennanprysthon/GCMS-Rennan-Prysthon#2]
- [x] Instalar Git localmente
- [x] Criar projeto local
- [x] Criar repositorio local e realizar commits
- [x] Subir alteracoes no repositorio da turma
